### ISSUE TITLE
Kyrth smells

### ISSUE THREAD

**Issue by HoustonDad** [CpanelInc/ea-apache2#2]
Can we fix?

wow can I edit someone else's comment? I am Perk hear me RAWR!

**Comment by HoustonDad** [comment]
Nope, sorry.

**Comment by 357r4bd** [comment]
No, impossible to fix.

**Comment by drmuey** [comment]
👍 

XML-SOAP won't do it eh?

**Comment by HoustonDad** [comment]
Test again

**Comment by 357r4bd** [comment]
I think the only thing that might get close is Acme::Bleach, but the memory overhead might be exceed 16TB.

**Comment by skurtn** [comment]
It's nice to know that my hygiene rigors (or lack thereof) are working as designed.
