### ISSUE TITLE
error_log allover

### ISSUE THREAD

**Issue by surjit** [CpanelInc/ea-apache2#4]
if syntax error or other errors in php
error_log file is generated in current directory, I want it to generate /home/$user/error_log
which file is responsible for this

**Comment by drmuey** [comment]
Hello @surjit,

You can accomplish this using [the `error_log` directive](http://php.net/manual/en/errorfunc.configuration.php#ini.error-log) in your global or user level PHP INI.

You can use the PHP INI editor in WHM to set it globally and the one in cPanel to set it at a user/vhost level.

HTH!
